### PR TITLE
Add disable button functionality for empty form

### PR DESCRIPTION
**Pull request by dkwon1223**
# Pull Request
## Description
[Add disable button functionality for empty form inputs.]
## Related Issues
[Iteration 1 Bullet Point 2]
## Screenshots (if applicable)
[N/A]
## Changes Made
[The function handleInput along with tweaks to the form submission event listener implement functionality that disables the save button when one or both of the title and body text inputs are not filled. The save button responds to empty form inputs by turning grey when clicked along with a disabled cursor.]
## Testing
[Manual testing by leaving either title or body or both inputs blank and attempting to save ideas.]
## Checklist
- [x] The code follows the project's coding standards.
- [ ] Unit tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes (if applicable).
- [x] The code compiles without errors.
- [x] The changes have been tested locally and pass all relevant tests.
- [ ] All new and existing tests pass.
- [x] The pull request has been reviewed by at least one other contributor.
## Reviewer Instructions
[Provide any specific instructions or information that would help the reviewer understand the context or nuances of the changes.]
## Deployment Notes
[Include any notes or instructions related to the deployment of this pull request, if applicable.]
## Additional Information
[Add any additional information that may be relevant to the review or understanding of the changes. This could include performance considerations, dependencies, or other relevant details.]

### CODE REVIEW

**Comment by BrandonDoza** [comment]
Looks Great!

**Comment by pareesakd1118** [comment]
all good!!

**Review by BrandonDoza — COMMENTED** [review]
Great Job!

**Review by AsherSpurr — COMMENTED** [review]
Looks great, i'm so happy y'all got the .disabled method working!! Let's add into the save button id - ont size as 190%, remove the padding from the card class, change the background color of the card to white, and edit edit indentation in JS

**Pull request merged**
