### PR TITLE
Revise CSS styling and sizing for responsiveness to window resizing

### PR DESCRIPTION
**Pull request by dkwon1223**
# Pull Request
## Description
[Revise CSS styling and sizing for responsiveness to window resizing]
## Related Issues
[Responsive styling]
## Screenshots (if applicable)
[N/A]
## Changes Made
[Revisions primarily consist of dimensions being altered from hard coded pixel units to percentages or other units that will allow the site to resize based on the browser window/monitor size.]
## Testing
[Testing was done manually with the team by trying different window sizes.]
## Checklist
- [x] The code follows the project's coding standards.
- [ ] Unit tests have been added or updated to cover the changes.
- [ ] Documentation has been updated to reflect the changes (if applicable).
- [x] The code compiles without errors.
- [x] The changes have been tested locally and pass all relevant tests.
- [ ] All new and existing tests pass.
- [x] The pull request has been reviewed by at least one other contributor.
## Reviewer Instructions
[N/A]
## Deployment Notes
[N/A]
## Additional Information
[N/A]

### CODE REVIEW

**Comment by BrandonDoza** [comment]
Looks good!

**Review by BrandonDoza — COMMENTED** [review]
Looks great!

**Comment by AsherSpurr** [comment]
Really great work figuring out how to get the webpage to re-size. This will be incredibly beneficial to workflow since we can now all see the page as it should be on various displays.

**Comment by pareesakd1118** [comment]
approved!

**Pull request merged**
